### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RomkeVdMeulen** [StoneAgeFactorio/StoneAgeFactorio#3]
0.1.0 (alpha release)

- [x] Lock mining based on held tool
- [ ] Change mining yield based on held tool
- [ ] Randomly spread entities throughout starting area
- [ ] Add items and recipes to progress to iron axe

Near future

- [ ] Multiplayer support (#2)
- [ ] Expensive recipe support
- [ ] Respect starting area size setting
